#!/bin/bash

yes | pkg update
pkg install wget -y

termux-setup-storage
yes | pkg update

BASE_URL="https://shouko.store"

DEST_DIR="/sdcard/Download"

for i in {1..10}; do
    FILE_NAME="CodexLite$i.apk"
    APK_PATH="$DEST_DIR/$FILE_NAME"

    echo "📥 Đang tải $FILE_NAME ..."
    wget -O "$APK_PATH" "$BASE_URL/$FILE_NAME"

    echo "Đang cài đặt $FILE_NAME ..."
    su -c "pm install -r $APK_PATH"
done

echo "Hoàn tất tải & cài 10 file"
