#!/bin/bash

yes | pkg update
pkg install -y aria2

termux-setup-storage
yes | pkg update

BASE_URL="https://shouko.store"
DEST_DIR="/sdcard/Download"

echo "📥 Đang tải nhanh ArceusXLite1–10 ..."
aria2c -x 16 -s 16 -d "$DEST_DIR" \
  "$BASE_URL/ArceusXLite1.apk" \
  "$BASE_URL/ArceusXLite2.apk" \
  "$BASE_URL/ArceusXLite3.apk" \
  "$BASE_URL/ArceusXLite4.apk" \
  "$BASE_URL/ArceusXLite5.apk" \
  "$BASE_URL/ArceusXLite6.apk" \
  "$BASE_URL/ArceusXLite7.apk" \
  "$BASE_URL/ArceusXLite8.apk" \
  "$BASE_URL/ArceusXLite9.apk" \
  "$BASE_URL/ArceusXLite10.apk"

for i in {1..10}; do
    FILE_NAME="ArceusXLite$i.apk"
    APK_PATH="$DEST_DIR/$FILE_NAME"

    echo "📦 Đang cài $FILE_NAME ..."
    su -c "pm install -r $APK_PATH"
done

echo "✅ Hoàn tất tải & cài ArceusXLite"
