#!/bin/bash

yes | pkg update
pkg install wget -y

termux-setup-storage
yes | pkg update

echo "📥 Đang tải CodeX APK..."
wget -O ~/storage/Download/Codex1 .apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Download/Codex2.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Download/Codex3.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex4.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex5.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex6.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex7.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex8.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex9.apk "https://shouko.store/CodexLite.apk"
echo "📥 Đang tải CodeX APK..."
wget -O ~/sdcard/Downloads/Codex10.apk "https://shouko.store/CodexLite.apk"
su -c "pm install -r /sdcard/Download/Codex1.apk"
su -c "pm install -r /sdcard/Download/Codex2.apk"
su -c "pm install -r /sdcard/Download/Codex3.apk"
su -c "pm install -r /sdcard/Download/Codex4.apk"
su -c "pm install -r /sdcard/Download/Codex5.apk"
su -c "pm install -r /sdcard/Download/Codex6.apk"
su -c "pm install -r /sdcard/Download/Codex7.apk"
su -c "pm install -r /sdcard/Download/Codex8.apk"
su -c "pm install -r /sdcard/Download/Codex9.apk"
su -c "pm install -r /sdcard/Download/Codex10.apk"
