#!/bin/bash

yes | pkg update
pkg install wget -y

termux-setup-storage
yes | pkg update

# Domain chung
BASE_URL="https://shouko.store"

# Thư mục lưu file
DEST_DIR="/sdcard/Download"

# Tải & cài lần lượt CodexLite1.apk → CodexLite10.apk
for i in {1..10}; do
    FILE_NAME="CodexLite$i.apk"
    APK_PATH="$DEST_DIR/$FILE_NAME"

    echo "📥 Đang tải $FILE_NAME ..."
    wget -O "$APK_PATH" "$BASE_URL/$FILE_NAME"

    echo "📦 Đang cài đặt $FILE_NAME ..."
    su -c "pm install -r $APK_PATH"
done

echo "✅ Hoàn tất tải & cài 10 file"
