#!/bin/bash
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
yes | pkg update
pkg install wget -y
. <(curl https://raw.githubusercontent.com/u400822/setup-termux/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade
yes | pkg i python
yes | pkg i python-pip
pip install requests pytz pyjwt pycryptodome rich colorama flask psutil discord python-socketio
curl -Ls "https://cdn.shouko.dev/RokidManager/neyoshiiuem/main/__main_loader__.py" -o /sdcard/Download/shouko.py
echo "📥 Đang tải Frostware APK..."
wget -O /sdcard/Download/frostware.apk "https://cdn.discordapp.com/attachments/1394580806583975966/1396106204660498432/FrostwareGlobalCloneMcye_01_2.679.1763.apk?ex=687ce0b9&is=687b8f39&hm=ba518574bf8cd2233704701c991e2da17e439fdeffcf759af7fc8abf6033f5e7"

echo "📥 Đang tải Frostware APK..."
wget -O /sdcard/Download/frostware1.apk "https://cdn.discordapp.com/attachments/1394580806583975966/1396113881679527946/FrostwareGlobalCloneMcye_02_2.679.1763.apk?ex=687ce7df&is=687b965f&hm=b67cb80a7e65f335e356fcacbf3ce9b735b895574fc18203a3f040605f525eda&"

echo "📥 Đang tải MT2 APK..."
wget -O /sdcard/Download/mt2.apk "https://pan.mt2.cn/mt/MT2.18.5.apk"

am start -a android.intent.action.VIEW -d "file:///sdcard/Download/frostware.apk" -t application/vnd.android.package-archive
am start -a android.intent.action.VIEW -d "file:///sdcard/Download/frostware1.apk" -t application/vnd.android.package-archive
am start -a android.intent.action.VIEW -d "file:///sdcard/Download/mt2.apk" -t application/vnd.android.package-archive
