#!/bin/bash


APK_DIR="/sdcard/Download"

APK_URL="https://shouko.store/CodexLite.apk"


for i in {1..10}; do
    APK_PATH="$APK_DIR/Codex$i.apk"
    echo "📥 Đang tải $APK_PATH ..."
    wget -O "$APK_PATH" "$APK_URL"
done


for i in {1..10}; do
    APK_PATH="$APK_DIR/Codex$i.apk"
    echo "📦 Đang cài đặt $APK_PATH ..."
    su -c "pm install -r $APK_PATH"
done
